# Generated by Django 3.1.5 on 2021-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_contactus_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studNo', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('emailid', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=20)),
                ('paymentType', models.CharField(max_length=20)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
