# Generated by Django 3.1.5 on 2021-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emailid',
            field=models.EmailField(max_length=150),
        ),
    ]
